/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AppRouteImport } from './routes/_app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppDashboardRouteImport } from './routes/_app.dashboard'
import { Route as AppTecnicosIndexRouteImport } from './routes/_app.tecnicos.index'
import { Route as AppOrdensServicoIndexRouteImport } from './routes/_app.ordens-servico.index'
import { Route as AppMateriaisIndexRouteImport } from './routes/_app.materiais.index'
import { Route as AppClientesIndexRouteImport } from './routes/_app.clientes.index'
import { Route as AppAtendentesIndexRouteImport } from './routes/_app.atendentes.index'
import { Route as AppAgendaIndexRouteImport } from './routes/_app.agenda.index'
import { Route as AppTecnicosNovoRouteImport } from './routes/_app.tecnicos.novo'
import { Route as AppTecnicosIdRouteImport } from './routes/_app.tecnicos.$id'
import { Route as AppOrdensServicoNovaRouteImport } from './routes/_app.ordens-servico.nova'
import { Route as AppMateriaisNovoRouteImport } from './routes/_app.materiais.novo'
import { Route as AppMateriaisIdRouteImport } from './routes/_app.materiais.$id'
import { Route as AppClientesNovoRouteImport } from './routes/_app.clientes.novo'
import { Route as AppClientesIdRouteImport } from './routes/_app.clientes.$id'
import { Route as AppAtendentesNovoRouteImport } from './routes/_app.atendentes.novo'
import { Route as AppAtendentesIdRouteImport } from './routes/_app.atendentes.$id'
import { Route as AppTecnicosIdEditarRouteImport } from './routes/_app.tecnicos.$id.editar'
import { Route as AppOrdensServicoIdGerenciarRouteImport } from './routes/_app.ordens-servico.$id.gerenciar'
import { Route as AppOrdensServicoIdEditarRouteImport } from './routes/_app.ordens-servico.$id.editar'
import { Route as AppMateriaisIdEditarRouteImport } from './routes/_app.materiais.$id.editar'
import { Route as AppClientesIdEditarRouteImport } from './routes/_app.clientes.$id.editar'
import { Route as AppAtendentesIdEditarRouteImport } from './routes/_app.atendentes.$id.editar'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppTecnicosIndexRoute = AppTecnicosIndexRouteImport.update({
  id: '/tecnicos/',
  path: '/tecnicos/',
  getParentRoute: () => AppRoute,
} as any)
const AppOrdensServicoIndexRoute = AppOrdensServicoIndexRouteImport.update({
  id: '/ordens-servico/',
  path: '/ordens-servico/',
  getParentRoute: () => AppRoute,
} as any)
const AppMateriaisIndexRoute = AppMateriaisIndexRouteImport.update({
  id: '/materiais/',
  path: '/materiais/',
  getParentRoute: () => AppRoute,
} as any)
const AppClientesIndexRoute = AppClientesIndexRouteImport.update({
  id: '/clientes/',
  path: '/clientes/',
  getParentRoute: () => AppRoute,
} as any)
const AppAtendentesIndexRoute = AppAtendentesIndexRouteImport.update({
  id: '/atendentes/',
  path: '/atendentes/',
  getParentRoute: () => AppRoute,
} as any)
const AppAgendaIndexRoute = AppAgendaIndexRouteImport.update({
  id: '/agenda/',
  path: '/agenda/',
  getParentRoute: () => AppRoute,
} as any)
const AppTecnicosNovoRoute = AppTecnicosNovoRouteImport.update({
  id: '/tecnicos/novo',
  path: '/tecnicos/novo',
  getParentRoute: () => AppRoute,
} as any)
const AppTecnicosIdRoute = AppTecnicosIdRouteImport.update({
  id: '/tecnicos/$id',
  path: '/tecnicos/$id',
  getParentRoute: () => AppRoute,
} as any)
const AppOrdensServicoNovaRoute = AppOrdensServicoNovaRouteImport.update({
  id: '/ordens-servico/nova',
  path: '/ordens-servico/nova',
  getParentRoute: () => AppRoute,
} as any)
const AppMateriaisNovoRoute = AppMateriaisNovoRouteImport.update({
  id: '/materiais/novo',
  path: '/materiais/novo',
  getParentRoute: () => AppRoute,
} as any)
const AppMateriaisIdRoute = AppMateriaisIdRouteImport.update({
  id: '/materiais/$id',
  path: '/materiais/$id',
  getParentRoute: () => AppRoute,
} as any)
const AppClientesNovoRoute = AppClientesNovoRouteImport.update({
  id: '/clientes/novo',
  path: '/clientes/novo',
  getParentRoute: () => AppRoute,
} as any)
const AppClientesIdRoute = AppClientesIdRouteImport.update({
  id: '/clientes/$id',
  path: '/clientes/$id',
  getParentRoute: () => AppRoute,
} as any)
const AppAtendentesNovoRoute = AppAtendentesNovoRouteImport.update({
  id: '/atendentes/novo',
  path: '/atendentes/novo',
  getParentRoute: () => AppRoute,
} as any)
const AppAtendentesIdRoute = AppAtendentesIdRouteImport.update({
  id: '/atendentes/$id',
  path: '/atendentes/$id',
  getParentRoute: () => AppRoute,
} as any)
const AppTecnicosIdEditarRoute = AppTecnicosIdEditarRouteImport.update({
  id: '/editar',
  path: '/editar',
  getParentRoute: () => AppTecnicosIdRoute,
} as any)
const AppOrdensServicoIdGerenciarRoute =
  AppOrdensServicoIdGerenciarRouteImport.update({
    id: '/ordens-servico/$id/gerenciar',
    path: '/ordens-servico/$id/gerenciar',
    getParentRoute: () => AppRoute,
  } as any)
const AppOrdensServicoIdEditarRoute =
  AppOrdensServicoIdEditarRouteImport.update({
    id: '/ordens-servico/$id/editar',
    path: '/ordens-servico/$id/editar',
    getParentRoute: () => AppRoute,
  } as any)
const AppMateriaisIdEditarRoute = AppMateriaisIdEditarRouteImport.update({
  id: '/editar',
  path: '/editar',
  getParentRoute: () => AppMateriaisIdRoute,
} as any)
const AppClientesIdEditarRoute = AppClientesIdEditarRouteImport.update({
  id: '/editar',
  path: '/editar',
  getParentRoute: () => AppClientesIdRoute,
} as any)
const AppAtendentesIdEditarRoute = AppAtendentesIdEditarRouteImport.update({
  id: '/editar',
  path: '/editar',
  getParentRoute: () => AppAtendentesIdRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/dashboard': typeof AppDashboardRoute
  '/atendentes/$id': typeof AppAtendentesIdRouteWithChildren
  '/atendentes/novo': typeof AppAtendentesNovoRoute
  '/clientes/$id': typeof AppClientesIdRouteWithChildren
  '/clientes/novo': typeof AppClientesNovoRoute
  '/materiais/$id': typeof AppMateriaisIdRouteWithChildren
  '/materiais/novo': typeof AppMateriaisNovoRoute
  '/ordens-servico/nova': typeof AppOrdensServicoNovaRoute
  '/tecnicos/$id': typeof AppTecnicosIdRouteWithChildren
  '/tecnicos/novo': typeof AppTecnicosNovoRoute
  '/agenda/': typeof AppAgendaIndexRoute
  '/atendentes/': typeof AppAtendentesIndexRoute
  '/clientes/': typeof AppClientesIndexRoute
  '/materiais/': typeof AppMateriaisIndexRoute
  '/ordens-servico/': typeof AppOrdensServicoIndexRoute
  '/tecnicos/': typeof AppTecnicosIndexRoute
  '/atendentes/$id/editar': typeof AppAtendentesIdEditarRoute
  '/clientes/$id/editar': typeof AppClientesIdEditarRoute
  '/materiais/$id/editar': typeof AppMateriaisIdEditarRoute
  '/ordens-servico/$id/editar': typeof AppOrdensServicoIdEditarRoute
  '/ordens-servico/$id/gerenciar': typeof AppOrdensServicoIdGerenciarRoute
  '/tecnicos/$id/editar': typeof AppTecnicosIdEditarRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/dashboard': typeof AppDashboardRoute
  '/atendentes/$id': typeof AppAtendentesIdRouteWithChildren
  '/atendentes/novo': typeof AppAtendentesNovoRoute
  '/clientes/$id': typeof AppClientesIdRouteWithChildren
  '/clientes/novo': typeof AppClientesNovoRoute
  '/materiais/$id': typeof AppMateriaisIdRouteWithChildren
  '/materiais/novo': typeof AppMateriaisNovoRoute
  '/ordens-servico/nova': typeof AppOrdensServicoNovaRoute
  '/tecnicos/$id': typeof AppTecnicosIdRouteWithChildren
  '/tecnicos/novo': typeof AppTecnicosNovoRoute
  '/agenda': typeof AppAgendaIndexRoute
  '/atendentes': typeof AppAtendentesIndexRoute
  '/clientes': typeof AppClientesIndexRoute
  '/materiais': typeof AppMateriaisIndexRoute
  '/ordens-servico': typeof AppOrdensServicoIndexRoute
  '/tecnicos': typeof AppTecnicosIndexRoute
  '/atendentes/$id/editar': typeof AppAtendentesIdEditarRoute
  '/clientes/$id/editar': typeof AppClientesIdEditarRoute
  '/materiais/$id/editar': typeof AppMateriaisIdEditarRoute
  '/ordens-servico/$id/editar': typeof AppOrdensServicoIdEditarRoute
  '/ordens-servico/$id/gerenciar': typeof AppOrdensServicoIdGerenciarRoute
  '/tecnicos/$id/editar': typeof AppTecnicosIdEditarRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/_app/dashboard': typeof AppDashboardRoute
  '/_app/atendentes/$id': typeof AppAtendentesIdRouteWithChildren
  '/_app/atendentes/novo': typeof AppAtendentesNovoRoute
  '/_app/clientes/$id': typeof AppClientesIdRouteWithChildren
  '/_app/clientes/novo': typeof AppClientesNovoRoute
  '/_app/materiais/$id': typeof AppMateriaisIdRouteWithChildren
  '/_app/materiais/novo': typeof AppMateriaisNovoRoute
  '/_app/ordens-servico/nova': typeof AppOrdensServicoNovaRoute
  '/_app/tecnicos/$id': typeof AppTecnicosIdRouteWithChildren
  '/_app/tecnicos/novo': typeof AppTecnicosNovoRoute
  '/_app/agenda/': typeof AppAgendaIndexRoute
  '/_app/atendentes/': typeof AppAtendentesIndexRoute
  '/_app/clientes/': typeof AppClientesIndexRoute
  '/_app/materiais/': typeof AppMateriaisIndexRoute
  '/_app/ordens-servico/': typeof AppOrdensServicoIndexRoute
  '/_app/tecnicos/': typeof AppTecnicosIndexRoute
  '/_app/atendentes/$id/editar': typeof AppAtendentesIdEditarRoute
  '/_app/clientes/$id/editar': typeof AppClientesIdEditarRoute
  '/_app/materiais/$id/editar': typeof AppMateriaisIdEditarRoute
  '/_app/ordens-servico/$id/editar': typeof AppOrdensServicoIdEditarRoute
  '/_app/ordens-servico/$id/gerenciar': typeof AppOrdensServicoIdGerenciarRoute
  '/_app/tecnicos/$id/editar': typeof AppTecnicosIdEditarRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/dashboard'
    | '/atendentes/$id'
    | '/atendentes/novo'
    | '/clientes/$id'
    | '/clientes/novo'
    | '/materiais/$id'
    | '/materiais/novo'
    | '/ordens-servico/nova'
    | '/tecnicos/$id'
    | '/tecnicos/novo'
    | '/agenda/'
    | '/atendentes/'
    | '/clientes/'
    | '/materiais/'
    | '/ordens-servico/'
    | '/tecnicos/'
    | '/atendentes/$id/editar'
    | '/clientes/$id/editar'
    | '/materiais/$id/editar'
    | '/ordens-servico/$id/editar'
    | '/ordens-servico/$id/gerenciar'
    | '/tecnicos/$id/editar'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/dashboard'
    | '/atendentes/$id'
    | '/atendentes/novo'
    | '/clientes/$id'
    | '/clientes/novo'
    | '/materiais/$id'
    | '/materiais/novo'
    | '/ordens-servico/nova'
    | '/tecnicos/$id'
    | '/tecnicos/novo'
    | '/agenda'
    | '/atendentes'
    | '/clientes'
    | '/materiais'
    | '/ordens-servico'
    | '/tecnicos'
    | '/atendentes/$id/editar'
    | '/clientes/$id/editar'
    | '/materiais/$id/editar'
    | '/ordens-servico/$id/editar'
    | '/ordens-servico/$id/gerenciar'
    | '/tecnicos/$id/editar'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/login'
    | '/_app/dashboard'
    | '/_app/atendentes/$id'
    | '/_app/atendentes/novo'
    | '/_app/clientes/$id'
    | '/_app/clientes/novo'
    | '/_app/materiais/$id'
    | '/_app/materiais/novo'
    | '/_app/ordens-servico/nova'
    | '/_app/tecnicos/$id'
    | '/_app/tecnicos/novo'
    | '/_app/agenda/'
    | '/_app/atendentes/'
    | '/_app/clientes/'
    | '/_app/materiais/'
    | '/_app/ordens-servico/'
    | '/_app/tecnicos/'
    | '/_app/atendentes/$id/editar'
    | '/_app/clientes/$id/editar'
    | '/_app/materiais/$id/editar'
    | '/_app/ordens-servico/$id/editar'
    | '/_app/ordens-servico/$id/gerenciar'
    | '/_app/tecnicos/$id/editar'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/dashboard': {
      id: '/_app/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/tecnicos/': {
      id: '/_app/tecnicos/'
      path: '/tecnicos'
      fullPath: '/tecnicos/'
      preLoaderRoute: typeof AppTecnicosIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/ordens-servico/': {
      id: '/_app/ordens-servico/'
      path: '/ordens-servico'
      fullPath: '/ordens-servico/'
      preLoaderRoute: typeof AppOrdensServicoIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/materiais/': {
      id: '/_app/materiais/'
      path: '/materiais'
      fullPath: '/materiais/'
      preLoaderRoute: typeof AppMateriaisIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/clientes/': {
      id: '/_app/clientes/'
      path: '/clientes'
      fullPath: '/clientes/'
      preLoaderRoute: typeof AppClientesIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/atendentes/': {
      id: '/_app/atendentes/'
      path: '/atendentes'
      fullPath: '/atendentes/'
      preLoaderRoute: typeof AppAtendentesIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/agenda/': {
      id: '/_app/agenda/'
      path: '/agenda'
      fullPath: '/agenda/'
      preLoaderRoute: typeof AppAgendaIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/tecnicos/novo': {
      id: '/_app/tecnicos/novo'
      path: '/tecnicos/novo'
      fullPath: '/tecnicos/novo'
      preLoaderRoute: typeof AppTecnicosNovoRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/tecnicos/$id': {
      id: '/_app/tecnicos/$id'
      path: '/tecnicos/$id'
      fullPath: '/tecnicos/$id'
      preLoaderRoute: typeof AppTecnicosIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/ordens-servico/nova': {
      id: '/_app/ordens-servico/nova'
      path: '/ordens-servico/nova'
      fullPath: '/ordens-servico/nova'
      preLoaderRoute: typeof AppOrdensServicoNovaRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/materiais/novo': {
      id: '/_app/materiais/novo'
      path: '/materiais/novo'
      fullPath: '/materiais/novo'
      preLoaderRoute: typeof AppMateriaisNovoRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/materiais/$id': {
      id: '/_app/materiais/$id'
      path: '/materiais/$id'
      fullPath: '/materiais/$id'
      preLoaderRoute: typeof AppMateriaisIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/clientes/novo': {
      id: '/_app/clientes/novo'
      path: '/clientes/novo'
      fullPath: '/clientes/novo'
      preLoaderRoute: typeof AppClientesNovoRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/clientes/$id': {
      id: '/_app/clientes/$id'
      path: '/clientes/$id'
      fullPath: '/clientes/$id'
      preLoaderRoute: typeof AppClientesIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/atendentes/novo': {
      id: '/_app/atendentes/novo'
      path: '/atendentes/novo'
      fullPath: '/atendentes/novo'
      preLoaderRoute: typeof AppAtendentesNovoRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/atendentes/$id': {
      id: '/_app/atendentes/$id'
      path: '/atendentes/$id'
      fullPath: '/atendentes/$id'
      preLoaderRoute: typeof AppAtendentesIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/tecnicos/$id/editar': {
      id: '/_app/tecnicos/$id/editar'
      path: '/editar'
      fullPath: '/tecnicos/$id/editar'
      preLoaderRoute: typeof AppTecnicosIdEditarRouteImport
      parentRoute: typeof AppTecnicosIdRoute
    }
    '/_app/ordens-servico/$id/gerenciar': {
      id: '/_app/ordens-servico/$id/gerenciar'
      path: '/ordens-servico/$id/gerenciar'
      fullPath: '/ordens-servico/$id/gerenciar'
      preLoaderRoute: typeof AppOrdensServicoIdGerenciarRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/ordens-servico/$id/editar': {
      id: '/_app/ordens-servico/$id/editar'
      path: '/ordens-servico/$id/editar'
      fullPath: '/ordens-servico/$id/editar'
      preLoaderRoute: typeof AppOrdensServicoIdEditarRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/materiais/$id/editar': {
      id: '/_app/materiais/$id/editar'
      path: '/editar'
      fullPath: '/materiais/$id/editar'
      preLoaderRoute: typeof AppMateriaisIdEditarRouteImport
      parentRoute: typeof AppMateriaisIdRoute
    }
    '/_app/clientes/$id/editar': {
      id: '/_app/clientes/$id/editar'
      path: '/editar'
      fullPath: '/clientes/$id/editar'
      preLoaderRoute: typeof AppClientesIdEditarRouteImport
      parentRoute: typeof AppClientesIdRoute
    }
    '/_app/atendentes/$id/editar': {
      id: '/_app/atendentes/$id/editar'
      path: '/editar'
      fullPath: '/atendentes/$id/editar'
      preLoaderRoute: typeof AppAtendentesIdEditarRouteImport
      parentRoute: typeof AppAtendentesIdRoute
    }
  }
}

interface AppAtendentesIdRouteChildren {
  AppAtendentesIdEditarRoute: typeof AppAtendentesIdEditarRoute
}

const AppAtendentesIdRouteChildren: AppAtendentesIdRouteChildren = {
  AppAtendentesIdEditarRoute: AppAtendentesIdEditarRoute,
}

const AppAtendentesIdRouteWithChildren = AppAtendentesIdRoute._addFileChildren(
  AppAtendentesIdRouteChildren,
)

interface AppClientesIdRouteChildren {
  AppClientesIdEditarRoute: typeof AppClientesIdEditarRoute
}

const AppClientesIdRouteChildren: AppClientesIdRouteChildren = {
  AppClientesIdEditarRoute: AppClientesIdEditarRoute,
}

const AppClientesIdRouteWithChildren = AppClientesIdRoute._addFileChildren(
  AppClientesIdRouteChildren,
)

interface AppMateriaisIdRouteChildren {
  AppMateriaisIdEditarRoute: typeof AppMateriaisIdEditarRoute
}

const AppMateriaisIdRouteChildren: AppMateriaisIdRouteChildren = {
  AppMateriaisIdEditarRoute: AppMateriaisIdEditarRoute,
}

const AppMateriaisIdRouteWithChildren = AppMateriaisIdRoute._addFileChildren(
  AppMateriaisIdRouteChildren,
)

interface AppTecnicosIdRouteChildren {
  AppTecnicosIdEditarRoute: typeof AppTecnicosIdEditarRoute
}

const AppTecnicosIdRouteChildren: AppTecnicosIdRouteChildren = {
  AppTecnicosIdEditarRoute: AppTecnicosIdEditarRoute,
}

const AppTecnicosIdRouteWithChildren = AppTecnicosIdRoute._addFileChildren(
  AppTecnicosIdRouteChildren,
)

interface AppRouteChildren {
  AppDashboardRoute: typeof AppDashboardRoute
  AppAtendentesIdRoute: typeof AppAtendentesIdRouteWithChildren
  AppAtendentesNovoRoute: typeof AppAtendentesNovoRoute
  AppClientesIdRoute: typeof AppClientesIdRouteWithChildren
  AppClientesNovoRoute: typeof AppClientesNovoRoute
  AppMateriaisIdRoute: typeof AppMateriaisIdRouteWithChildren
  AppMateriaisNovoRoute: typeof AppMateriaisNovoRoute
  AppOrdensServicoNovaRoute: typeof AppOrdensServicoNovaRoute
  AppTecnicosIdRoute: typeof AppTecnicosIdRouteWithChildren
  AppTecnicosNovoRoute: typeof AppTecnicosNovoRoute
  AppAgendaIndexRoute: typeof AppAgendaIndexRoute
  AppAtendentesIndexRoute: typeof AppAtendentesIndexRoute
  AppClientesIndexRoute: typeof AppClientesIndexRoute
  AppMateriaisIndexRoute: typeof AppMateriaisIndexRoute
  AppOrdensServicoIndexRoute: typeof AppOrdensServicoIndexRoute
  AppTecnicosIndexRoute: typeof AppTecnicosIndexRoute
  AppOrdensServicoIdEditarRoute: typeof AppOrdensServicoIdEditarRoute
  AppOrdensServicoIdGerenciarRoute: typeof AppOrdensServicoIdGerenciarRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppDashboardRoute: AppDashboardRoute,
  AppAtendentesIdRoute: AppAtendentesIdRouteWithChildren,
  AppAtendentesNovoRoute: AppAtendentesNovoRoute,
  AppClientesIdRoute: AppClientesIdRouteWithChildren,
  AppClientesNovoRoute: AppClientesNovoRoute,
  AppMateriaisIdRoute: AppMateriaisIdRouteWithChildren,
  AppMateriaisNovoRoute: AppMateriaisNovoRoute,
  AppOrdensServicoNovaRoute: AppOrdensServicoNovaRoute,
  AppTecnicosIdRoute: AppTecnicosIdRouteWithChildren,
  AppTecnicosNovoRoute: AppTecnicosNovoRoute,
  AppAgendaIndexRoute: AppAgendaIndexRoute,
  AppAtendentesIndexRoute: AppAtendentesIndexRoute,
  AppClientesIndexRoute: AppClientesIndexRoute,
  AppMateriaisIndexRoute: AppMateriaisIndexRoute,
  AppOrdensServicoIndexRoute: AppOrdensServicoIndexRoute,
  AppTecnicosIndexRoute: AppTecnicosIndexRoute,
  AppOrdensServicoIdEditarRoute: AppOrdensServicoIdEditarRoute,
  AppOrdensServicoIdGerenciarRoute: AppOrdensServicoIdGerenciarRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
